### ISSUE TITLE
Cannot find module "./components"

### ISSUE THREAD

**Issue by jackmcdade** [appcomponents/material-components#4] opened 2016-04-22 20:45 UTC
When requiring with Vueify, I get the error `Cannot find module "./components"`.

```
require('vue-material-components/dist/vue-material-components')
```

**Comment by BigBlueHat** [comment] 2016-05-03 15:00
I also get this when using the files pulled from the `dist/` folder (per the readme).

Would love to use this, but I'm stuck. :disappointed:

**Comment by mjanys** [comment] 2016-05-03 18:46
I am not strong at webpack. Did you try something like 
webpack.js:
```
 module: {
      include: [
        path.resolve('./vue-material-components/dist/vue-material-components)
      ],
}
```

**Comment by jackmcdade** [comment] 2016-05-03 18:49
I'm not using webpack, i'm using browserify.

**Comment by efealatan** [comment] 2016-05-06 17:28
Any updates?

**Comment by doublenian** [comment] 2016-05-08 10:36
below is my code 
```
import Vue from 'vue'
import VueMaterial from 'vue-material-components'

VueMaterial.registerAll();
for (var i = 0; i < VueMaterial.mixins.length; i++) {
    Vue.mixin(VueMaterial.mixins[i]);
}
```
I got same error : Cannot find module './components',I don't know how to fix it ,please try it ,and tell me 
how to fixed,thank you!

**Comment by mjanys** [comment] 2016-05-08 10:49
I'm not using browserify,
if someone creates minimal project that I can simply try build and it will fail. I'll have a look on it ;)

**Comment by efealatan** [comment] 2016-05-09 12:03
Im on web pack

**Comment by efealatan** [comment] 2016-05-09 12:30
just a thought but could the issue be in the way that you dist. Cause->  Cannot find module "./components" could mean that it needs the components folder in its path, no?

**Comment by mariaczi** [comment] 2016-05-11 08:01
I have the same issue. Love this package already but can't start...

**Comment by taylorzane** [comment] 2016-05-11 18:37
The issue is with the `webpack.config.js`. It's not resolving modules correctly.

I've created a pull request (#8) to resolve this issue. You can use that repo commit in the meantime, or you can modify the `webpack.config.js` file manually in `node_modules/vue-material-components/`. I've tested this with a known working Vue.js webpack config.

I will also post this to the SO question for greater visibility.

**Comment by mariaczi** [comment] 2016-05-11 18:48
@taylorzane How do you configure usage in main.js ?
It looked like RegisterAll not working at all. All components where unrecognized.

**Comment by taylorzane** [comment] 2016-05-11 19:00
Did you update the `webpack.config.js` file? I was able to simply copy-paste @doublenian's snippet.

**Comment by taylorzane** [comment] 2016-05-11 19:00
You have to also run an `npm install && npm run dist`. I forgot to mention that in my original post.

**Comment by mariaczi** [comment] 2016-05-11 19:25
@taylorzane hi, I tried but I can't npm install...
```
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v5.10.1
npm ERR! npm  v3.8.3
npm ERR! path E:\***\resources\assets\js\ep_panel\node_
modules\vue-material-components
npm ERR! code EBUSY
npm ERR! errno -4082
npm ERR! syscall rename

npm ERR! EBUSY: resource busy or locked, rename 'E:\****\node_modules\vue-material-components' -> 'E:\***\node_modules\.vue-material-
components.DELETE'
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     E:\***\node_m
odules\vue-material-components\npm-debug.log
npm ERR! code 1
```

**Comment by mjanys** [comment] 2016-05-12 05:37
https://github.com/appcomponents/material-components/pull/8

**Comment by mariaczi** [comment] 2016-05-12 10:49
Can you rebuild and push it to npm? I am not able to install it and rebuild as I am getting above errors.

**Comment by mjanys** [comment] 2016-05-12 17:16
Very good idea, It is done vue-material-components@0.1.2

**Comment by mariaczi** [comment] 2016-05-12 18:31
I am so sorry but it is still not working...
What I have in my main.js:
```
import VueMaterial from 'vue-material-components'
VueMaterial.registerAll();
```

`Vue.use('VueMaterial')` does not work

I've tried with:
```
var VueMaterial = require('vue-material-components');
VueMaterial.registerAll();
```

and it still does not work..

Components are just not registered. It renders them exactly with code.

Any idea why, what's wrong? It has to be something in your code I think as any other libs are working.

**Comment by taylorzane** [comment] 2016-05-12 21:15
The reason this is happening is because the `registerAll` method isn't referencing the same Vue instance. In order to get this to work, one would need to implement an `install` method and use the `Vue.use` syntax so that the same Vue instance is being referenced. A work-around until that happens is this syntax:

```js
import VueMaterial from 'vue-material-components'
for (const materialComponent in VueMaterial.components) {
  Vue.component(materialComponent, VueMaterial.components[materialComponent])
}
```

**Comment by mariaczi** [comment] 2016-05-12 22:20
@taylorzane oh my! Thank you!!!! I was already going to use bootstrap components.. now I can use this nice lib!
Can you please advice or create pull request with necessary changes into this package to make it working without work around?

THANK YOU!

**Comment by taylorzane** [comment] 2016-05-12 23:02
Sure. I'll submit a PR this evening, or tomorrow morning, to get this working as expected.

**Comment by mariaczi** [comment] 2016-05-13 10:30
@taylorzane  Am I right that it will also cure warning from webpack about another module with the same name but different case?
```
WARNING in ./~/vue/dist/vue.common.js
There is another module with an equal name when case is ignored.
This can lead to unexpected behavior when compiling on a filesystem with other c
ase-semantic.
Rename module if multiple modules are expected or use equal casing if one module
 is expected.

WARNING in ./~/Vue/dist/vue.common.js
There is another module with an equal name when case is ignored.
This can lead to unexpected behavior when compiling on a filesystem with other c
ase-semantic.
Rename module if multiple modules are expected or use equal casing if one module
 is expected.
```

**Comment by taylorzane** [comment] 2016-05-13 14:22
Yep! This would definitely resolve that webpack warning.

**Comment by taylorzane** [comment] 2016-05-13 14:48
I'm looking through the codebase and there are multiple things that are causing this error. It's not something that I would be comfortable with doing as it would be quite an overhaul on the library. I'll still submit the PR that fixes the installation, but the other issues will have to be directed towards the maintainers.

**Comment by mariaczi** [comment] 2016-05-13 14:50
@taylorzane I think it would be useful to explain it to @mjanys as I think he wants to improve this library. It is probably some big, but still refactor, not writing it again?

**Comment by taylorzane** [comment] 2016-05-13 15:06
It's definitely just a refactor. What needs to happen is all reference of `Vue = require('vue')` or `VueModule = require('vue')` in the codebase needs to be removed. Most places are an easy fix, but it's a matter of refactoring your code to not depend on Vue until the install phase is complete.

@mjanys You can reach out to me if you need a better explanation or need help refactoring. This is just beyond the current issue.

**Comment by taylorzane** [comment] 2016-05-13 15:07
I have submitted PR #11 to use the `Vue.use` syntax.

**Comment by mjanys** [comment] 2016-05-14 07:14
Sorry guy I'm totally out of time. If taylorzane could do PR, it is welcome. I'll check it asap and merge

**Comment by doublenian** [comment] 2016-05-28 15:29
@mjanys Hello,can you fix the `WARNING in ./~/Vue/dist/vue.common.js` problem( this take the Vue root scope and affect the HMR) just talk about above.
I do not know about typescript,and can not fix it。so if  you can fix it ,it can be perfect 。 thank you,I wish you can

**Comment by mjanys** [comment] 2016-05-28 16:22
Well, I would like but I'm not using Vueify,
I just did what taylorzane said and I've removed all `required('vue')`, try it in branch https://github.com/appcomponents/material-components/tree/issue-4-removing-vue-require, please

**Comment by doublenian** [comment] 2016-05-28 16:44
I compile the source ,and use the dist js, but same problem with the error.

<img width="837" alt="8f50a4b5-f3d6-4db8-a11b-4f296957d5f5" src="https://cloud.githubusercontent.com/assets/2343611/15628561/821f659c-2536-11e6-847d-ab073a46867a.png">

**Comment by mjanys** [comment] 2016-05-28 16:49
Are you using vue-material-components by this way?
```
<script src="http://cdnjs.cloudflare.com/ajax/libs/vue/1.0.24/vue.min.js"></script>
<script src="dist/vue-material-components.min.js"></script>
<script>
    Vue.use(VueMaterialComponents)

    new Vue({
        el: '#content'
    })
</script>
```

Is vue really linked to document ?

**Comment by mjanys** [comment] 2016-06-04 17:40
Can somebody try it with branch https://github.com/appcomponents/material-components/tree/issue-4-removing-vue-require ?

**Comment by mjanzs** [comment] 2016-06-11 10:59
closing, I did changes that was mentioned here and another changes, if it is still present I can reopen it

**Closed by mjanzs** 2016-06-11 10:59 UTC

**Comment by tinnvec** [comment] 2016-06-24 18:57
I believe I'm getting the same issue on Travis CI
```js
import Vue from 'vue'
import VueResource from 'vue-resource'
Vue.use(VueMaterialComponents)
```
```sh
Error: Cannot find module 'Vue' from '/home/travis/build/tinnvec/decal/node_modules/vue-material-components/dist'
    at /home/travis/build/tinnvec/decal/node_modules/resolve/lib/async.js:46:17
    at process (/home/travis/build/tinnvec/decal/node_modules/resolve/lib/async.js:173:43)
    at ondir (/home/travis/build/tinnvec/decal/node_modules/resolve/lib/async.js:188:17)
    at load (/home/travis/build/tinnvec/decal/node_modules/resolve/lib/async.js:69:43)
    at onex (/home/travis/build/tinnvec/decal/node_modules/resolve/lib/async.js:92:31)
    at /home/travis/build/tinnvec/decal/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:82:15)
```

**Comment by mariaczi** [comment] 2016-06-24 19:39
I may be wrong but you don't import it before Vue.use which you should do

pt., 24 cze 2016, 19:57 użytkownik Alex Hanna <notifications@github.com>
napisał:

**Comment by tinnvec** [comment] 2016-06-24 20:07
My apologies, @mariaczi, I removed the wrong line when cleaning up imports to paste here. I've updated my comment to reflect the way I have it set up.
